# Generated by Django 2.2.4 on 2020-12-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201223_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
