# Generated by Django 2.2.4 on 2020-12-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201223_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliver', models.ManyToManyField(related_name='delivered', to='app.Driver')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.User')),
            ],
        ),
    ]
