# Generated by Django 2.2.4 on 2020-12-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201226_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
