# Generated by Django 2.2.4 on 2020-12-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201226_1426'),
        ('app', '0006_auto_20201226_2009'),
    ]

    operations = [
    ]
